# Pull the latest Nginx image from Docker Hub
FROM nginx:latest

# Copy the index.html file into the container
COPY index.html /usr/share/nginx/html/index.html

# Copy the nginx.conf file into the container
COPY nginx.conf /etc/nginx/conf.d/default.conf
